# Generated by Django 3.1.2 on 2021-01-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_auto_20210127_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date, time')),
                ('received', models.DateField(verbose_name='Received date')),
                ('channel', models.SmallIntegerField(choices=[(1, 'Электронная почта Актива'), (2, 'Электронная почта Корпорации'), (3, 'Бумажная почта'), (4, 'Лично'), (5, 'Форма обратной связи на сайте'), (6, 'Телефонный звонок')], default=1, verbose_name='Received channel')),
                ('received_text', models.TextField(blank=True, null=True, verbose_name='Core of the problem')),
                ('client_contact', models.CharField(max_length=200, verbose_name='Contacts client')),
                ('forwarded', models.DateField(blank=True, null=True, verbose_name='Forwarded date')),
                ('forwarded_to_emp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Employee whom forwarded item')),
                ('status', models.SmallIntegerField(choices=[(0, 'В работе'), (1, 'Завершено')], default=0, verbose_name='Forwarded item status')),
                ('action', models.CharField(blank=True, max_length=300, null=True, verbose_name='Action by answer')),
                ('status_answer', models.SmallIntegerField(blank=True, choices=[(0, 'Информация подтвердилась'), (1, 'Информация подтвердилась частично'), (2, 'Информация не подтвердилась')], default=0, null=True, verbose_name='Answer status')),
                ('damage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlineitems', to='reference.company', verbose_name='Company')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.subcategoryhotline', verbose_name='Hotline subcategory')),
            ],
            options={
                'ordering': ['-received'],
            },
        ),
        migrations.CreateModel(
            name='HotLineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(max_length=200)),
                ('hotline_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotline_files', to='hotline.hotlineitem')),
            ],
        ),
        migrations.CreateModel(
            name='HotLineComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Comment date')),
                ('user_name', models.CharField(max_length=100, verbose_name='User name')),
                ('hotline_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotline_comments', to='hotline.hotlineitem')),
            ],
        ),
    ]
