# Generated by Django 3.1.2 on 2021-01-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_auto_20210128_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlinefile',
            name='file',
        ),
        migrations.AlterField(
            model_name='hotlinefile',
            name='hotline_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotline.hotlineitem'),
        ),
    ]
