# Generated by Django 3.1.2 on 2021-01-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0005_auto_20210128_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlinefile',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
