# Generated by Django 3.1.2 on 2021-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_hotlinefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlinecomment',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='hotlinefile',
            name='hotline_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotline_files', to='hotline.hotlineitem'),
        ),
    ]
