# Generated by Django 3.1.2 on 2021-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0007_auto_20210129_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlineitem',
            name='closed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Closed date'),
        ),
    ]
