# Generated by Django 3.1.2 on 2020-10-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=150, verbose_name='Короткое название')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное название')),
                ('inn', models.IntegerField(verbose_name='ИНН компании')),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование процесса')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование риска')),
            ],
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование подпроцесса')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='reference.process', verbose_name='Процесс верхнего уровня')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='Период показателей')),
                ('actives', models.FloatField(verbose_name='Активы организации')),
                ('earn', models.FloatField(verbose_name='Выручка')),
                ('cost_price', models.FloatField(verbose_name='Себестоимость')),
                ('oibda', models.FloatField(verbose_name='OIBDA')),
                ('net_profit', models.FloatField(verbose_name='Чистая прибыль')),
                ('count_employee', models.IntegerField(verbose_name='Количество сотрудников')),
                ('count_employee_ia', models.IntegerField(verbose_name='Количество сотрудников ВА')),
                ('budget_ia', models.FloatField(verbose_name='Бюджет ВА')),
                ('costs_ia', models.FloatField(verbose_name='Затраты ВА')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_data_companies', to='reference.company', verbose_name='Организация')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
    ]
