# Generated by Django 3.1.2 on 2021-02-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0003_auto_20210127_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edit date')),
                ('employee', models.CharField(max_length=100, verbose_name='Edit date')),
                ('employee_position', models.CharField(max_length=100, verbose_name='Edit date')),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Need action'), (2, 'Finished')], default=0, verbose_name='Status ethic item')),
                ('question_1', models.BooleanField(verbose_name='question_1')),
                ('question_1_comment', models.TextField(blank=True, null=True, verbose_name='question 1 comment')),
                ('question_2', models.BooleanField(verbose_name='question_2')),
                ('question_3', models.BooleanField(verbose_name='question_3')),
                ('question_4', models.BooleanField(verbose_name='question_4')),
                ('question_5', models.BooleanField(verbose_name='question_5')),
                ('question_6', models.BooleanField(verbose_name='question_6')),
                ('question_6_comment', models.TextField(blank=True, null=True, verbose_name='question 6 comment')),
                ('question_7', models.BooleanField(verbose_name='question_7')),
                ('question_7_comment', models.TextField(blank=True, null=True, verbose_name='question 7 comment')),
                ('question_8', models.BooleanField(verbose_name='question_8')),
                ('question_8_comment', models.TextField(blank=True, null=True, verbose_name='question 8 comment')),
                ('question_9', models.BooleanField(verbose_name='question_9')),
                ('question_9_comment', models.TextField(blank=True, null=True, verbose_name='question 9 comment')),
                ('question_10', models.BooleanField(verbose_name='question_10')),
                ('question_10_comment', models.TextField(blank=True, null=True, verbose_name='question 10 comment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['status', '-created'],
            },
        ),
    ]
