# Generated by Django 3.1.2 on 2021-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethiccertification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_10',
            new_name='answer_10',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_10_comment',
            new_name='answer_10_comment',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_1_comment',
            new_name='answer_1_comment',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_4',
            new_name='answer_4',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_5',
            new_name='answer_5',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_6',
            new_name='answer_6',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_6_comment',
            new_name='answer_6_comment',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_7',
            new_name='answer_7',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_7_comment',
            new_name='answer_7_comment',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_8',
            new_name='answer_8',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_8_comment',
            new_name='answer_8_comment',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_9',
            new_name='answer_9',
        ),
        migrations.RenameField(
            model_name='ethicitem',
            old_name='question_9_comment',
            new_name='answer_9_comment',
        ),
        migrations.AlterField(
            model_name='ethicitem',
            name='employee',
            field=models.CharField(max_length=100, verbose_name='Employee name'),
        ),
        migrations.AlterField(
            model_name='ethicitem',
            name='employee_position',
            field=models.CharField(max_length=100, verbose_name='Employee position'),
        ),
    ]
