# Generated by Django 3.1.2 on 2021-02-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethiccertification', '0002_auto_20210202_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicItemAnswer3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_status', models.SmallIntegerField(choices=[(0, 'Я'), (1, 'Родственник'), (2, 'Доверенный представитель')], verbose_name='Relations status')),
                ('FIO', models.CharField(max_length=100, verbose_name='FIO')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('ethic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethic_item_answers_3', to='ethiccertification.ethicitem', verbose_name='Company')),
            ],
        ),
    ]
