# Generated by Django 3.1.2 on 2021-02-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20210127_1757'),
        ('ethiccertification', '0004_auto_20210204_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicItemAnswer5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree (in family)')),
                ('FIO', models.CharField(max_length=100, verbose_name='FIO')),
                ('position', models.CharField(max_length=100, verbose_name='Position in company')),
                ('impact', models.BooleanField(verbose_name='Impact yes/no')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.company', verbose_name='Company')),
                ('ethic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethic_item_answers_5', to='ethiccertification.ethicitem', verbose_name='Ethic item')),
            ],
        ),
        migrations.CreateModel(
            name='EthicItemAnswer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_status', models.SmallIntegerField(choices=[(0, 'Я'), (1, 'Родственник'), (2, 'Доверенный представитель')], verbose_name='Relations status')),
                ('FIO', models.CharField(max_length=100, verbose_name='FIO')),
                ('share_of_capital', models.SmallIntegerField(verbose_name='Share of capital, %')),
                ('relation_to_corporation', models.SmallIntegerField(choices=[(0, 'Не в группе АФК'), (1, 'В группе АФК')], default=0, verbose_name='Relation to AFK')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Company name')),
                ('company_INN', models.CharField(blank=True, max_length=10, null=True, verbose_name='Company INN')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('ethic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethic_item_answers_2', to='ethiccertification.ethicitem', verbose_name='Ethic item')),
            ],
        ),
    ]
